# Generated by Django 5.0.2 on 2026-07-09 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ib', '0078_remove_business_businessbadge_and_more'),
        ('interior_engine', '0002_relabel_contenttypes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='BusinessBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('imageUrl', models.URLField(blank=True, max_length=2250, null=True)),
                ('isDefault', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app_ib_businessbadge',
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageSQUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('imageRTUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
                ('shortValue', models.CharField(blank=True, max_length=250, null=True)),
                ('trending', models.BooleanField(default=False)),
                ('index', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_ib_businesscategory',
            },
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageSQUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('imageRTUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
                ('trending', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app_ib_businesstype',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'app_ib_socialmedia',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=250)),
                ('brandName', models.CharField(blank=True, max_length=250, null=True)),
                ('rating', models.CharField(blank=True, default='3.5', max_length=3, null=True)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('coverImageUrl', models.TextField(blank=True, default='', null=True)),
                ('bannerImageUrl', models.TextField(blank=True, default='', null=True)),
                ('bannerLink', models.TextField(blank=True, default='', null=True)),
                ('bannerText', models.TextField(blank=True, default='', null=True)),
                ('gst', models.CharField(blank=True, max_length=250, null=True)),
                ('since', models.CharField(blank=True, max_length=250, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('selfCreated', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('ratingValue', models.FloatField(default=0.0)),
                ('totalReviews', models.PositiveIntegerField(default=0)),
                ('ratingBreakdown', models.JSONField(blank=True, default=dict)),
                ('trendingScore', models.FloatField(db_index=True, default=0.0)),
                ('hotScore', models.FloatField(db_index=True, default=0.0)),
                ('viewCount', models.PositiveIntegerField(default=0)),
                ('leadCount', models.PositiveIntegerField(default=0)),
                ('isVerified', models.BooleanField(default=False)),
                ('completionPercent', models.PositiveIntegerField(default=0)),
                ('canGoLive', models.BooleanField(default=False)),
                ('avgResponseSeconds', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('expertiseTags', models.ManyToManyField(blank=True, related_name='expert_businesses', to='interior_engine.tag')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_business', to=settings.AUTH_USER_MODEL)),
                ('businessBadge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior_business.businessbadge')),
                ('businessCategory', models.ManyToManyField(related_name='business_category', to='interior_business.businesscategory')),
            ],
            options={
                'db_table': 'app_ib_business',
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryImageUrl', models.TextField(blank=True, default='', null=True)),
                ('secondaryImagesUrl', models.TextField(blank=True, default='', null=True)),
                ('about', models.TextField()),
                ('youtubeLink', models.TextField()),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='interior_business.business')),
            ],
            options={
                'db_table': 'app_ib_businessprofile',
            },
        ),
        migrations.CreateModel(
            name='BusinessSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageSQUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('imageRTUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
                ('shortValue', models.CharField(blank=True, max_length=250, null=True)),
                ('trending', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('businessCategory', models.ManyToManyField(blank=True, related_name='business_category_segment', to='interior_business.businesscategory')),
                ('businessType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_type_segment', to='interior_business.businesstype')),
            ],
            options={
                'db_table': 'app_ib_businesssegment',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='businessSegment',
            field=models.ManyToManyField(related_name='business_segment', to='interior_business.businesssegment'),
        ),
        migrations.AddField(
            model_name='business',
            name='businessType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior_business.businesstype'),
        ),
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('isWorking', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='interior_business.business')),
            ],
            options={
                'db_table': 'app_ib_dayschedule',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinCode', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('locationLink', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_location', to='interior_business.business')),
                ('locationCountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ib.country')),
                ('locationState', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ib.state')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_location',
            },
        ),
        migrations.CreateModel(
            name='BusinessSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessSocialMedia', to='interior_business.business')),
                ('socialMedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialMediaBusiness', to='interior_business.socialmedia')),
            ],
            options={
                'db_table': 'app_ib_businesssocialmedia',
            },
        ),
            ],
            database_operations=[],
        ),
    ]
