# Generated by Django 5.0.2 on 2026-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_business', '0002_relabel_contenttypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='avgProjectValue',
            field=models.PositiveIntegerField(blank=True, help_text='Average project value in rupees. null = cell omitted from the KPI grid.', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='coaRegistered',
            field=models.BooleanField(default=False, help_text="Council-of-Architecture registered → 'COA registered' credential chip."),
        ),
        migrations.AddField(
            model_name='business',
            name='liabilityInsured',
            field=models.BooleanField(default=False, help_text="Carries liability insurance → 'Liability insured' credential chip."),
        ),
    ]
