# Generated by Django 5.0.2 on 2026-07-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_business', '0003_business_avgprojectvalue_business_coaregistered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='businessModel',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='cin',
            field=models.CharField(blank=True, default='', help_text='Company Identification Number.', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='founderName',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='pan',
            field=models.CharField(blank=True, default='', help_text='PAN.', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='productPriceTiers',
            field=models.JSONField(blank=True, default=list, help_text='Product price-tier labels the seller serves.'),
        ),
        migrations.AddField(
            model_name='business',
            name='teamSize',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='udyam',
            field=models.CharField(blank=True, default='', help_text='Udyam / MSME registration number.', max_length=50),
        ),
    ]
