# Generated by Django 5.0.2 on 2026-07-09 19:05

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Delete-then-create: the models leave app_ib state in 0076 before they
        # are re-registered here (state-only move — same app_ib_* tables).
        ('app_ib', '0076_delete_banners_remove_blog_user_delete_constants_and_more'),
    ]

    operations = [
        # State-only: the app_ib_* tables already exist — this move keeps them in
        # place and only re-registers the CMS models under interior_cms (TASK 16).
        migrations.SeparateDatabaseAndState(database_operations=[], state_operations=[
        migrations.CreateModel(
            name='OfferHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app_ib_offerheading',
            },
        ),
        migrations.CreateModel(
            name='OfferText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_quill.fields.QuillField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=2250, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('show', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app_ib_offertext',
            },
        ),
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=2250)),
                ('name', models.CharField(max_length=2250)),
                ('index', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'app_ib_ourclients',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'stockimages page',
                'db_table': 'app_ib_page',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', django_quill.fields.QuillField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'information pages',
                'db_table': 'app_ib_pages',
            },
        ),
        migrations.CreateModel(
            name='QNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app_ib_qna',
            },
        ),
        migrations.CreateModel(
            name='ReelSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(max_length=2250)),
                ('name', models.CharField(max_length=2250)),
                ('index', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'app_ib_reelsection',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app_ib_section',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('initials', models.CharField(blank=True, default='', max_length=6)),
                ('gradient', models.CharField(blank=True, default='', max_length=200)),
                ('photoUrl', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('isPlaceholder', models.BooleanField(default=False)),
                ('displayOrder', models.PositiveIntegerField(db_index=True, default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_ib_teammember',
                'ordering': ['displayOrder', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.CharField(blank=True, max_length=800, null=True, unique=True)),
                ('cover', models.FileField(blank=True, null=True, upload_to='blog/cover')),
                ('coverImageUrl', models.TextField(blank=True, default='', null=True)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('author', models.TextField()),
                ('authorImageUrl', models.URLField(blank=True, default='', null=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('featuredOrder', models.PositiveIntegerField(default=0)),
                ('metaTitle', models.CharField(blank=True, default='', max_length=300)),
                ('metaDescription', models.TextField(blank=True, default='')),
                ('focusKeyword', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_blog',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(default='blog', max_length=30)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_newslettersubscriber',
            },
        ),
        migrations.CreateModel(
            name='StockMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=2250, null=True)),
                ('video', models.URLField(blank=True, max_length=2250, null=True)),
                ('index', models.IntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interior_cms.page')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interior_cms.section')),
            ],
            options={
                'db_table': 'app_ib_stockmedia',
            },
        ),
        ]),
    ]
