# Generated by Django 5.0.2 on 2025-10-25 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ib', '0040_customuser_selfcreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catelogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catelougeImage', models.URLField()),
                ('catelougePdf', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('totalDownload', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ib.business')),
                ('catelogueType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_ib.businesstype')),
            ],
        ),
    ]
