# Generated by Django 5.0.2 on 2025-11-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
                ('imageSQUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('imageRTUrl', models.CharField(blank=True, max_length=2250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catelogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catelougeImage', models.URLField()),
                ('catelougePdf', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('totalDownload', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('ytLink', models.URLField(blank=True, null=True)),
                ('index', models.IntegerField(default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catelogues', to='app_ib.business')),
                ('catelogueType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_ib.businesstype')),
                ('catalogCategory', models.ManyToManyField(related_name='catCatelogues', to='interior_products.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CatelogueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catelougeImage', models.URLField()),
                ('index', models.IntegerField(default=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('catelouge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catelogueImages', to='interior_products.catelogue')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('index', models.IntegerField(default=1)),
                ('orignalPrice', models.FloatField()),
                ('discountType', models.CharField(max_length=50)),
                ('displayPrice', models.FloatField()),
                ('discountBy', models.FloatField()),
                ('description', models.TextField()),
                ('productTags', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_ib.business')),
                ('catelogue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='interior_products.catelogue')),
                ('category', models.ManyToManyField(related_name='catProducts', to='interior_products.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('index', models.IntegerField(default=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='interior_products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSpecifications', to='interior_products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
                ('imageSQUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('imageRTUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodsubcat', to='interior_products.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ManyToManyField(related_name='subcatProducts', to='interior_products.productsubcategory'),
        ),
        migrations.AddField(
            model_name='catelogue',
            name='subCategory',
            field=models.ManyToManyField(related_name='catSubCatelogues', to='interior_products.productsubcategory'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('orignalPrice', models.FloatField()),
                ('discountType', models.CharField(max_length=50)),
                ('displayPrice', models.FloatField()),
                ('discountBy', models.FloatField()),
                ('description', models.TextField()),
                ('serviceTags', models.TextField()),
                ('index', models.IntegerField(default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_ib.business')),
                ('category', models.ManyToManyField(related_name='catServices', to='interior_products.productcategory')),
                ('subCategory', models.ManyToManyField(related_name='subcatServices', to='interior_products.productsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('index', models.IntegerField(default=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceImages', to='interior_products.service')),
            ],
        ),
    ]
