# Generated by Django 5.0.2 on 2025-10-27 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catelogue',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='catelogue',
            name='ytLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CatelogueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catelougeImage', models.URLField()),
                ('index', models.IntegerField(default=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('catelouge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catelogueImages', to='interior_products.catelogue')),
            ],
        ),
    ]
