# Generated by Django 5.0.2 on 2025-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
                ('imageSQUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('imageRTUrl', models.CharField(blank=True, max_length=2250, null=True)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
