# Generated by Django 5.0.2 on 2025-11-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0002_interiorservices_productcategory_trending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiorservices',
            name='link',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
    ]
