# Generated by Django 5.0.2 on 2026-01-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0003_interiorservices_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='shortValue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='shortValue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
