# Generated by Django 5.0.2 on 2025-10-28 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0040_customuser_selfcreated'),
        ('interior_products', '0003_product_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('index', models.IntegerField(default=1)),
                ('orignalPrice', models.FloatField()),
                ('discountType', models.CharField(max_length=50)),
                ('displayPrice', models.FloatField()),
                ('discountBy', models.FloatField()),
                ('description', models.TextField()),
                ('productTags', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_ib.business')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('index', models.IntegerField(default=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceImages', to='interior_products.service')),
            ],
        ),
    ]
