# Generated by Django 5.0.2 on 2026-01-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0004_productcategory_shortvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catelogueimage',
            name='catelougeImage',
            field=models.URLField(max_length=2250),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(max_length=2250),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.URLField(max_length=2250),
        ),
    ]
