# Generated by Django 5.0.2 on 2025-10-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0004_service_serviceimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='productTags',
            new_name='serviceTags',
        ),
    ]
