# Generated by Django 5.0.2 on 2026-01-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0005_alter_catelogueimage_catelougeimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catelogue',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
