# Generated by Django 5.0.2 on 2025-10-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0005_rename_producttags_service_servicetags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimage',
            old_name='product',
            new_name='service',
        ),
    ]
