# Generated by Django 5.0.2 on 2026-01-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0006_catelogue_updatedat_product_updatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
