# Generated by Django 5.0.2 on 2025-11-07 06:44

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0006_rename_product_serviceimage_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catelogue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior_products.catelogue'),
        ),
        migrations.AddField(
            model_name='product',
            name='productDescription',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', django_quill.fields.QuillField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSpecifications', to='interior_products.product')),
            ],
        ),
    ]
