# Generated by Django 5.0.2 on 2026-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0019_dailysnapshot_fallbackvideo_feedevent_and_more'),
        ('interior_products', '0007_productcategory_index_productsubcategory_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='catelogue',
            name='hotScore',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='catelogue',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catelogue',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='catelogue',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='catelogue',
            name='trendingScore',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='catelogue',
            name='viewCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='hotScore',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ratingValue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stockQuantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='app_ib.tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='totalReviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='trendingScore',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='viewCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='hotScore',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='ratingValue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='serviceAreas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='stockQuantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='services', to='app_ib.tag'),
        ),
        migrations.AddField(
            model_name='service',
            name='totalReviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='trendingScore',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='viewCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
