# Generated by Django 5.0.2 on 2025-11-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0007_product_catelogue_product_productdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productDescription',
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
