# Generated by Django 5.0.2 on 2026-06-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0008_catelogue_hotscore_catelogue_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratingBreakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='ratingBreakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
