# Generated by Django 5.0.2 on 2025-11-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0008_remove_product_productdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='interior_products.productcategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ManyToManyField(to='interior_products.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interior_products.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ManyToManyField(to='interior_products.productsubcategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='subCategory',
            field=models.ManyToManyField(to='interior_products.productsubcategory'),
        ),
    ]
