# Generated by Django 5.0.2 on 2025-11-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0009_productcategory_product_category_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catelogue',
            name='subCategory',
            field=models.ManyToManyField(to='interior_products.productsubcategory'),
        ),
        migrations.RemoveField(
            model_name='catelogue',
            name='category',
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodsubcat', to='interior_products.productcategory'),
        ),
        migrations.AddField(
            model_name='catelogue',
            name='category',
            field=models.ManyToManyField(to='interior_products.productcategory'),
        ),
    ]
