# Generated by Django 5.0.2 on 2026-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0009_product_ratingbreakdown_service_ratingbreakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='isAvailable',
            field=models.BooleanField(default=True, help_text='Owner-controlled availability (accepting work right now). NOT the same as isActive, which means listed/unlisted.'),
        ),
    ]
