# Generated by Django 5.0.2 on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0010_service_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='catelogue',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='catelogue',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
