# Generated by Django 5.0.2 on 2025-11-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0010_catelogue_subcategory_remove_catelogue_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catelogue',
            name='catalogCategory',
            field=models.ManyToManyField(to='interior_products.productcategory'),
        ),
        migrations.RemoveField(
            model_name='catelogue',
            name='category',
        ),
        migrations.AddField(
            model_name='catelogue',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
