# Generated by Django 5.0.2 on 2025-11-14 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0047_businesssegment_businesscategory_and_more'),
        ('interior_products', '0011_catelogue_catalogcategory_remove_catelogue_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='imageRTUrl',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='imageSQUrl',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='imageRTUrl',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='imageSQUrl',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
        migrations.AlterField(
            model_name='catelogue',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catelogues', to='app_ib.business'),
        ),
        migrations.AlterField(
            model_name='catelogue',
            name='catalogCategory',
            field=models.ManyToManyField(related_name='catCatelogues', to='interior_products.productcategory'),
        ),
        migrations.AlterField(
            model_name='catelogue',
            name='subCategory',
            field=models.ManyToManyField(related_name='catSubCatelogues', to='interior_products.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='catProducts', to='interior_products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catelogue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='interior_products.catelogue'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.ManyToManyField(related_name='subcatProducts', to='interior_products.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ManyToManyField(related_name='catServices', to='interior_products.productcategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subCategory',
            field=models.ManyToManyField(related_name='subcatServices', to='interior_products.productsubcategory'),
        ),
    ]
