# Generated by Django 5.0.2 on 2026-07-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0012_servicefaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='careInstructions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='installationSteps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
