# Generated by Django 5.0.2 on 2026-07-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_engine', '0001_initial'),
        ('interior_products', '0013_product_careinstructions_product_installationsteps'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='interior_engine.tag'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='services', to='interior_engine.tag'),
        ),
            ],
        ),
    ]
