# Generated by Django 5.0.2 on 2026-07-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_business', '0001_initial'),
        ('interior_products', '0014_alter_product_tags_alter_service_tags'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.AlterField(
            model_name='catelogue',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catelogues', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='catelogue',
            name='catelogueType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_business.businesstype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='service',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='interior_business.business'),
        ),
            ],
            database_operations=[],
        ),
    ]
