# Generated by Django 5.0.2 on 2026-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0015_alter_catelogue_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minOrderQty',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum order quantity. null = no minimum (stepper starts at 1).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, default='', help_text="Country/region of origin, e.g. 'Italy'. Blank = no origin chip.", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='samplePrice',
            field=models.FloatField(blank=True, help_text='Price of a sample. null = no sample price shown.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sampleRefundable',
            field=models.BooleanField(default=False, help_text='Whether the sample price is refundable on order.'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='', help_text="Unit of measure, e.g. 'sq ft'. Blank falls back to 'units'.", max_length=30),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='group',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
