# Generated by Django 5.0.2 on 2026-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0016_product_minorderqty_product_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='turnaroundDays',
            field=models.PositiveIntegerField(blank=True, help_text='Typical turnaround in days, as stated by the seller. 0 = same day. null = not stated (the card shows no pill).', null=True),
        ),
    ]
