# Generated by Django 5.0.2 on 2026-07-20 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_products', '0017_service_turnarounddays'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricingModel',
            field=models.CharField(blank=True, choices=[('per_piece', 'Per piece'), ('per_unit', 'Per unit'), ('per_sqft', 'Per sqft'), ('per_meter', 'Per meter'), ('per_set', 'Per set'), ('custom', 'Custom quote')], default='', help_text="Pricing unit. Blank = not set (UI defaults to 'Per piece').", max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='stockStatus',
            field=models.CharField(blank=True, choices=[('in_stock', 'In stock'), ('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('made_to_order', 'Made to order')], default='', help_text='Stock availability. Blank = not set.', max_length=30),
        ),
        migrations.CreateModel(
            name='ProductBulkTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minQty', models.PositiveIntegerField(help_text='Minimum quantity for this tier.')),
                ('price', models.FloatField(help_text='Unit price at this tier.')),
                ('tierIndex', models.PositiveIntegerField(default=0, help_text='Display order (0 = first).')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulkTiers', to='interior_products.product')),
            ],
            options={
                'ordering': ['tierIndex'],
                'unique_together': {('product', 'tierIndex')},
            },
        ),
    ]
