# Generated by Django 5.0.2 on 2025-10-11 12:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0038_alter_business_updated_at'),
        ('interior_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('days', models.IntegerField()),
                ('priceTotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adCampaigns', to='app_ib.business')),
                ('approvalMode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_ads.adapprovalmode')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adCampaigns', to='interior_ads.adplacement')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_ads.adstatus')),
            ],
        ),
        migrations.CreateModel(
            name='AdAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3Key', models.TextField()),
                ('meta', models.JSONField(default=dict)),
                ('assetType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_ads.adassettype')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='interior_ads.adcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentProvider', models.TextField()),
                ('paymentReference', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='interior_ads.adcampaign')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_ads.adpaymentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='AdStatAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('formSubmissions', models.IntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='interior_ads.adcampaign')),
            ],
            options={
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AdStatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userSessionId', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='interior_ads.adcampaign')),
                ('eventType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_ads.adeventtype')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'eventType'], name='interior_ad_campaig_fdf9a1_idx')],
            },
        ),
    ]
