# Generated by Django 5.0.2 on 2025-10-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_ads', '0002_adcampaign_adasset_adpayment_adstataggregate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplacement',
            name='aspectRatio',
            field=models.CharField(choices=[('16:9', '16:9'), ('4:3', '4:3'), ('1:1', '1:1')], default='1:1', max_length=100),
        ),
    ]
