# Generated by Django 5.0.2 on 2025-10-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0038_alter_business_updated_at'),
        ('interior_ads', '0003_adplacement_aspectratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('ageBetween', models.CharField(blank=True, max_length=50, null=True)),
                ('personaType', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='interior_ads.adcampaign')),
                ('categories', models.ManyToManyField(blank=True, to='app_ib.businesscategory')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_ib.businesssegment')),
            ],
        ),
    ]
