# Generated by Django 5.0.2 on 2025-08-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planquery',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='planquery',
            name='country',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='planquery',
            name='state',
            field=models.CharField(default='', max_length=500),
        ),
    ]
