# Generated by Django 5.0.2 on 2025-11-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(default='', max_length=500)),
                ('transactionId', models.CharField(default='', max_length=500)),
                ('amount', models.CharField(default='', max_length=500)),
                ('paymentFor', models.CharField(default='', max_length=500)),
                ('createdAt', models.DateTimeField()),
                ('expiryAt', models.DateTimeField()),
                ('orderStatus', models.CharField(default='', max_length=500)),
                ('paymentSessionId', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
