# Generated by Django 5.0.2 on 2025-08-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0002_planquery_address_planquery_country_planquery_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessLocation',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='detail',
            new_name='youtube_link',
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='subscription/attachment'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_percentage',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payable_amount',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='subscription/pdf'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subtitle',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tag',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='title',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
