# Generated by Django 5.0.2 on 2025-11-20 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0002_transectiondata'),
        ('interior_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='catalouge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalouge_lead_query', to='interior_products.catelogue'),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lead_query', to='interior_products.product'),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_lead_query', to='interior_products.service'),
        ),
        migrations.AlterField(
            model_name='businesssegment',
            name='businessCategory',
            field=models.ManyToManyField(blank=True, related_name='business_category_segment', to='app_ib.businesscategory'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to=settings.AUTH_USER_MODEL),
        ),
    ]
