# Generated by Django 5.0.2 on 2025-08-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0003_rename_businesslocation_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='subscription',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='subscription/video'),
        ),
    ]
