# Generated by Django 5.0.2 on 2025-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0003_leadquery_catalouge_leadquery_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesssegment',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesstype',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
