# Generated by Django 5.0.2 on 2025-08-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0004_remove_subscription_youtube_link_subscription_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('name', models.CharField(blank=True, max_length=800, null=True)),
                ('phone', models.CharField(blank=True, max_length=800, null=True)),
                ('mail', models.CharField(blank=True, max_length=800, null=True)),
                ('company', models.CharField(blank=True, max_length=800, null=True)),
                ('recognisation', models.CharField(blank=True, max_length=800, null=True)),
                ('detail', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact/attachment')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
