# Generated by Django 5.0.2 on 2025-11-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0004_businesscategory_trending_businesssegment_trending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
