# Generated by Django 5.0.2 on 2025-12-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0005_businesscategory_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rating',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
