# Generated by Django 5.0.2 on 2025-12-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0006_business_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='rating',
            field=models.CharField(blank=True, default='3.5', max_length=3, null=True),
        ),
    ]
