# Generated by Django 5.0.2 on 2025-08-30 05:48

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0006_location_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', django_quill.fields.QuillField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
