# Generated by Django 5.0.2 on 2025-09-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0007_pages_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='primary_image_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='secondary_images_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
