# Generated by Django 5.0.2 on 2025-12-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0007_alter_business_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='availableDuration',
            field=models.JSONField(blank=True, default=list, help_text="List of objects with duration and price. Example: [{'duration': 3, 'price': 100}, {'duration': 6, 'price': 180}]", null=True),
        ),
    ]
