# Generated by Django 5.0.2 on 2025-09-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0008_businessprofile_primary_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
