# Generated by Django 5.0.2 on 2025-12-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0008_subscription_availableduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='offertext',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
