# Generated by Django 5.0.2 on 2026-01-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0009_offertext_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=2250)),
                ('name', models.CharField(max_length=2250)),
                ('index', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReelSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(max_length=2250)),
                ('name', models.CharField(max_length=2250)),
                ('index', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
