# Generated by Django 5.0.2 on 2025-09-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0009_business_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_image_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
