# Generated by Django 5.0.2 on 2026-01-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0010_ourclients_reelsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='shortValue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='businesssegment',
            name='shortValue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
