# Generated by Django 5.0.2 on 2025-09-06 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0010_business_cover_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='app_ib.business'),
        ),
        migrations.AlterField(
            model_name='location',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_location', to='app_ib.business'),
        ),
    ]
