# Generated by Django 5.0.2 on 2026-02-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0011_businesscategory_shortvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='leadStatus',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='stage',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
