# Generated by Django 5.0.2 on 2026-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0012_leadquery_leadstatus_leadquery_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='logs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
