# Generated by Django 5.0.2 on 2026-03-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0013_leadquery_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='text_password',
            field=models.CharField(blank=True, default='Test@123', max_length=500, null=True),
        ),
    ]
