# Generated by Django 5.0.2 on 2026-03-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0014_customuser_text_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='category',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
