# Generated by Django 5.0.2 on 2025-09-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0014_blog_cover_image_url_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=800, null=True, unique=True),
        ),
    ]
