# Generated by Django 5.0.2 on 2026-03-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0015_leadquery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='clientLogs',
            field=models.JSONField(blank=True, default=list, help_text="{'by':'client/business','message':'Text message','date':'date in dmy format(02-12-2026)'}", null=True),
        ),
    ]
