# Generated by Django 5.0.2 on 2026-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0016_leadquery_clientlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='leadcount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
