# Generated by Django 5.0.2 on 2025-09-10 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0016_blog_updated_at_business_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('image_url', models.URLField(blank=True, max_length=2250, null=True)),
                ('isDefault', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='badge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='businessBadge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ib.businessbadge'),
        ),
    ]
