# Generated by Django 5.0.2 on 2025-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0017_businessbadge_alter_business_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='fallback_image_url',
            field=models.URLField(blank=True, max_length=2250, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_pdf_url',
            field=models.URLField(blank=True, max_length=2250, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='video_url',
            field=models.URLField(blank=True, max_length=2250, null=True),
        ),
    ]
