# Generated by Django 5.0.2 on 2026-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0017_subscription_leadcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='buyIntent',
            field=models.CharField(blank=True, default='website', max_length=1000, null=True),
        ),
    ]
