# Generated by Django 5.0.2 on 2025-09-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0018_subscription_fallback_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='gst',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='since',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
