# Generated by Django 5.0.2 on 2026-04-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0018_businessplan_buyintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='selfCreated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='stage',
            field=models.TextField(blank=True, db_index=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='status',
            field=models.TextField(blank=True, db_index=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
