# Generated by Django 5.0.2 on 2025-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0019_alter_business_gst_alter_business_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadquery',
            name='city',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='country',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='email',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='interested',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='priority',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='query',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='state',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='tag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
