# Generated by Django 5.0.2 on 2026-06-10 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0019_dailysnapshot_fallbackvideo_feedevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='requested', max_length=20)),
                ('declineReason', models.CharField(blank=True, default='', max_length=255)),
                ('lastMessageAt', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='app_ib.business')),
                ('businessUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_conversations', to=settings.AUTH_USER_MODEL)),
                ('clientUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_conversations', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='app_ib.leadquery')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_ib.conversation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['clientUser', 'status'], name='app_ib_conv_clientU_3650f1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['businessUser', 'status'], name='app_ib_conv_busines_4d54c1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'createdAt'], name='app_ib_mess_convers_1b3934_idx'),
        ),
    ]
