# Generated by Django 5.0.2 on 2026-06-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0020_conversation_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoUrl', models.TextField()),
                ('thumbnailUrl', models.TextField(blank=True, default='')),
                ('authorName', models.CharField(max_length=150)),
                ('authorRole', models.CharField(blank=True, default='', max_length=150)),
                ('businessName', models.CharField(blank=True, default='', max_length=200)),
                ('quote', models.TextField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('isActive', models.BooleanField(default=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['index', '-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
