# Generated by Django 5.0.2 on 2025-09-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0020_alter_leadquery_city_alter_leadquery_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planquery',
            name='attachment_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
