# Generated by Django 5.0.2 on 2025-09-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0021_planquery_attachment_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quate',
            old_name='phone',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='quate',
            name='interested',
        ),
        migrations.AddField(
            model_name='quate',
            name='budget',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='quate',
            name='businessType',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='quate',
            name='city',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='quate',
            name='companyName',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='quate',
            name='leadType',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='quate',
            name='noOfEmp',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='quate',
            name='query',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quate',
            name='state',
            field=models.CharField(default='', max_length=500),
        ),
    ]
