# Generated by Django 5.0.2 on 2026-06-10 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0021_testimonial_shop_city_shop_lat_shop_lng_shop_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorsPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('eyebrow', models.CharField(default='', max_length=255)),
                ('headline', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
                ('trendTags', models.JSONField(blank=True, default=list)),
                ('imageUrl', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='template', max_length=20)),
                ('isPublished', models.BooleanField(default=True)),
                ('isAiEdited', models.BooleanField(default=False)),
                ('snapshotDate', models.DateField()),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors_picks', to='app_ib.architect')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('coverImage', models.TextField(blank=True, default='')),
                ('images', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('style', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('viewCount', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app_ib.architect')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app_ib.business')),
            ],
            options={
                'ordering': ['index', '-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='editorspick',
            constraint=models.UniqueConstraint(fields=('architect', 'snapshotDate'), name='uniq_editors_pick_day'),
        ),
    ]
