# Generated by Django 5.0.2 on 2025-09-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0022_rename_phone_quate_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('link', models.URLField(blank=True, max_length=2250, null=True)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'stockimages page'},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name_plural': 'information pages'},
        ),
        migrations.AlterModelOptions(
            name='quate',
            options={'verbose_name': 'Leads for company', 'verbose_name_plural': 'Platform Own Leads'},
        ),
    ]
