# Generated by Django 5.0.2 on 2026-06-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0022_editorspick_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='firstResponseSeconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlatformAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(default='inline', max_length=100)),
                ('eyebrow', models.CharField(blank=True, default='', max_length=255)),
                ('heading1', models.CharField(blank=True, default='', max_length=255)),
                ('heading2', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('buttonLabel', models.CharField(blank=True, default='', max_length=100)),
                ('buttonLink', models.TextField(blank=True, default='')),
                ('imageUrl', models.TextField(blank=True, default='')),
                ('theme', models.CharField(default='green', max_length=50)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('startsAt', models.DateTimeField(blank=True, null=True)),
                ('endsAt', models.DateTimeField(blank=True, null=True)),
                ('impressionCount', models.PositiveIntegerField(default=0)),
                ('clickCount', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='app_ib.adpage')),
            ],
            options={
                'ordering': ['placement', 'displayOrder', 'timestamp'],
            },
        ),
    ]
