# Generated by Django 5.0.2 on 2026-06-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0023_adpage_conversation_firstresponseseconds_platformad'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
