# Generated by Django 5.0.2 on 2025-09-26 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0023_offertext_alter_page_options_alter_pages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplan',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_plan', to='app_ib.business'),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_lead_query', to='app_ib.business'),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_lead_query', to=settings.AUTH_USER_MODEL),
        ),
    ]
