# Generated by Django 5.0.2 on 2025-09-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0024_alter_businessplan_business_alter_leadquery_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authorImage',
            field=models.URLField(blank=True, default='', help_text='add the url or the image', max_length=2250, null=True),
        ),
    ]
