# Generated by Django 5.0.2 on 2026-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0024_business_lat_business_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
