# Generated by Django 5.0.2 on 2025-09-29 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0024_alter_businessplan_business_alter_leadquery_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='businessCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ib.businesscategory'),
        ),
        migrations.CreateModel(
            name='BusinessSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('lable', models.CharField(max_length=250)),
                ('businessCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_category_segment', to='app_ib.businesscategory')),
                ('businessType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_type_segment', to='app_ib.businesstype')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='businessSegment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ib.businesssegment'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='businessType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_type_category', to='app_ib.businesstype'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ib.businesstype'),
        ),
    ]
