# Generated by Django 5.0.2 on 2025-09-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0025_businesscategory_businesstype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscategory',
            name='businessType',
        ),
        migrations.RemoveField(
            model_name='businesssegment',
            name='businessCategory',
        ),
    ]
