# Generated by Django 5.0.2 on 2026-06-13 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0025_customuser_preferred_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='entityType',
            field=models.CharField(blank=True, default='business', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='architect',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_architect', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArchitectPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(blank=True, default='')),
                ('amount', models.CharField(default='', max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('transactionId', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('planSummary', models.TextField(blank=True, default='')),
                ('lastActivate', models.DateTimeField(auto_now_add=True)),
                ('expireDate', models.DateTimeField(blank=True, null=True)),
                ('buyIntent', models.CharField(blank=True, default='website', max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='architect_plan', to='app_ib.architect')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ib.subscription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='architect_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(blank=True, default='')),
                ('amount', models.CharField(default='', max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('transactionId', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('planSummary', models.TextField(blank=True, default='')),
                ('lastActivate', models.DateTimeField(auto_now_add=True)),
                ('expireDate', models.DateTimeField(blank=True, null=True)),
                ('buyIntent', models.CharField(blank=True, default='website', max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ib.subscription')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_plan', to='app_ib.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
