# Generated by Django 5.0.2 on 2025-09-27 11:18

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0025_blog_authorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertext',
            name='text',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
