# Generated by Django 5.0.2 on 2025-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0026_remove_businesscategory_businesstype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='businessCategory',
        ),
        migrations.RemoveField(
            model_name='business',
            name='businessSegment',
        ),
        migrations.AddField(
            model_name='business',
            name='businessCategory',
            field=models.ManyToManyField(blank=True, null=True, to='app_ib.businesscategory'),
        ),
        migrations.AddField(
            model_name='business',
            name='businessSegment',
            field=models.ManyToManyField(blank=True, null=True, to='app_ib.businesssegment'),
        ),
    ]
