# Generated by Django 5.0.2 on 2025-09-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0027_remove_business_businesscategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('companyName', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('planType', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('plan', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('intrest', models.TextField(blank=True, default='', null=True)),
                ('need', models.TextField(blank=True, default='', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='New', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
