# Generated by Django 5.0.2 on 2026-06-16 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0027_architect_expertisetags_blog_featuredorder_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(default='blog', max_length=30)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('deviceLabel', models.CharField(blank=True, default='', max_length=120)),
                ('userAgent', models.TextField(blank=True, default='')),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('lastActiveAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('revokedAt', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-lastActiveAt'],
            },
        ),
        migrations.CreateModel(
            name='RelatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceObjectId', models.PositiveIntegerField(db_index=True)),
                ('targetObjectId', models.PositiveIntegerField()),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('reason', models.CharField(default='co_view', max_length=20)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('sourceContentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_source', to='contenttypes.contenttype')),
                ('targetContentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_target', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['sourceContentType', 'sourceObjectId', 'score'], name='app_ib_rela_sourceC_22ab5c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='relateditem',
            constraint=models.UniqueConstraint(fields=('sourceContentType', 'sourceObjectId', 'targetContentType', 'targetObjectId'), name='uniq_related_pair'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'revokedAt'], name='app_ib_user_user_id_f1590d_idx'),
        ),
    ]
