# Generated by Django 5.0.2 on 2025-09-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0028_funnelform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='businessCategory',
            field=models.ManyToManyField(to='app_ib.businesscategory'),
        ),
        migrations.AlterField(
            model_name='business',
            name='businessSegment',
            field=models.ManyToManyField(to='app_ib.businesssegment'),
        ),
    ]
