# Generated by Django 5.0.2 on 2026-06-18 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0028_newslettersubscriber_usersession_relateditem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.JSONField(blank=True, default=list)),
                ('profileSnapshot', models.TextField(blank=True, default='')),
                ('snapshotHash', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(default='template', max_length=20)),
                ('generatedAt', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='app_ib.business')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityType', models.CharField(default='business', max_length=20)),
                ('scheduledAt', models.DateTimeField(db_index=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=50)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lastError', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_jobs', to='app_ib.business')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduledAt'], name='app_ib_spec_status_8627f8_idx')],
            },
        ),
    ]
