# Generated by Django 5.0.2 on 2025-10-03 09:59

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0029_alter_business_businesscategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertext',
            name='text',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
