# Generated by Django 5.0.2 on 2026-06-20 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0029_businessspecialization_specializationjob'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('actorName', models.CharField(blank=True, default='', max_length=255)),
                ('verb', models.CharField(max_length=20)),
                ('entityType', models.CharField(blank=True, default='', max_length=20)),
                ('entityName', models.CharField(blank=True, default='', max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('isRead', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_made', to=settings.AUTH_USER_MODEL)),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'timestamp'], name='app_ib_enga_owner_i_a55b7f_idx'), models.Index(fields=['owner', 'isRead'], name='app_ib_enga_owner_i_4b6715_idx')],
            },
        ),
    ]
