# Generated by Django 5.0.2 on 2026-06-20 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0030_engagementactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectplan',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shopplan',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grantsEntityTypes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='planFamily',
            field=models.CharField(blank=True, default='business', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AutomationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(blank=True, default='')),
                ('amount', models.CharField(default='', max_length=500)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('isActive', models.BooleanField(default=False)),
                ('transactionId', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('planSummary', models.TextField(blank=True, default='')),
                ('lastActivate', models.DateTimeField(auto_now_add=True)),
                ('expireDate', models.DateTimeField(blank=True, null=True)),
                ('buyIntent', models.CharField(blank=True, default='website', max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_plan', to='app_ib.architect')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_plan', to='app_ib.business')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ib.subscription')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_plan', to='app_ib.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
