# Generated by Django 5.0.2 on 2025-10-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0031_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locationCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ib.country'),
        ),
        migrations.AddField(
            model_name='location',
            name='locationState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ib.state'),
        ),
    ]
