# Generated by Django 5.0.2 on 2025-10-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0032_location_locationcountry_location_locationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='countryCode',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
