# Generated by Django 5.0.2 on 2026-06-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0032_backfill_plan_status_and_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
