# Generated by Django 5.0.2 on 2025-10-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0033_userprofile_countrycode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessplan',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='expire_date',
            new_name='lastActivate',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='plan_summary',
            new_name='planSummary',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='last_activate',
        ),
        migrations.AddField(
            model_name='businessplan',
            name='amount',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='expireDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ib.subscription'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='transactionId',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
