# Generated by Django 5.0.2 on 2026-07-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0034_seed_legal_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Differentiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('iconBg', models.CharField(blank=True, default='', max_length=40)),
                ('iconColor', models.CharField(blank=True, default='', max_length=40)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('eliminates', models.JSONField(blank=True, default=list)),
                ('index', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['index', 'id'],
            },
        ),
    ]
