# Generated by Django 5.0.2 on 2025-10-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0034_rename_is_active_businessplan_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authorImageUrl',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
