# Generated by Django 5.0.2 on 2025-10-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0035_blog_authorimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
