# Generated by Django 5.0.2 on 2026-07-03 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0035_differentiator'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUsCta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='', max_length=200)),
                ('titleLead', models.CharField(blank=True, default='', max_length=200)),
                ('titleAccent', models.CharField(blank=True, default='', max_length=200)),
                ('sub', models.TextField(blank=True, default='')),
                ('primaryLabel', models.CharField(blank=True, default='', max_length=100)),
                ('primaryAction', models.JSONField(blank=True, default=dict)),
                ('secondaryLabel', models.CharField(blank=True, default='', max_length=100)),
                ('secondaryAction', models.JSONField(blank=True, default=dict)),
                ('trustBadges', models.JSONField(blank=True, default=list)),
                ('cardHead', models.CharField(blank=True, default='', max_length=200)),
                ('responseNote', models.CharField(blank=True, default='', max_length=300)),
                ('isActive', models.BooleanField(default=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JoinUsStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=40)),
                ('value', models.TextField(blank=True, default='')),
                ('index', models.PositiveIntegerField(default=0)),
                ('joinUs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app_ib.joinuscta')),
            ],
            options={
                'ordering': ['index', 'id'],
            },
        ),
    ]
