# Generated by Django 5.0.2 on 2026-07-04 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0036_joinuscta_joinusstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('badge', models.CharField(blank=True, default='', max_length=60)),
                ('color', models.CharField(blank=True, default='', max_length=40)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='app_ib.shop')),
            ],
            options={
                'ordering': ['displayOrder', '-timestamp'],
            },
        ),
    ]
