# Generated by Django 5.0.2 on 2025-10-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0036_alter_business_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
