# Generated by Django 5.0.2 on 2026-07-04 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0037_shopupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(blank=True, default='')),
                ('askedBy', models.CharField(blank=True, default='', max_length=120)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_ib.shop')),
            ],
            options={
                'ordering': ['displayOrder', '-timestamp'],
            },
        ),
    ]
