# Generated by Django 5.0.2 on 2025-10-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0037_alter_business_timestamp_alter_business_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
