# Generated by Django 5.0.2 on 2025-10-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0038_alter_business_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='selfCreated',
            field=models.BooleanField(default=False),
        ),
    ]
