# Generated by Django 5.0.2 on 2026-07-04 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0038_shopquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.TextField()),
                ('index', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_ib.shop')),
            ],
            options={
                'ordering': ['index', 'timestamp'],
            },
        ),
    ]
