# Generated by Django 5.0.2 on 2025-10-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0039_business_selfcreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selfCreated',
            field=models.BooleanField(default=False),
        ),
    ]
