# Generated by Django 5.0.2 on 2025-10-29 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0040_customuser_selfcreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='banner_image_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='BusinessSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessSocialMedia', to='app_ib.business')),
                ('socialMedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialMediaBusiness', to='app_ib.socialmedia')),
            ],
        ),
    ]
