# Generated by Django 5.0.2 on 2026-07-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0040_full_legal_page_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
