# Generated by Django 5.0.2 on 2025-11-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0041_socialmedia_business_banner_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bannerLink',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='bannerText',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
