# Generated by Django 5.0.2 on 2026-07-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0041_customuser_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='businessDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='clientDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
