# Generated by Django 5.0.2 on 2026-07-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0042_conversation_businessdeleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
