# Generated by Django 5.0.2 on 2025-11-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0043_dayschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
        migrations.AddField(
            model_name='businesssegment',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
        migrations.AddField(
            model_name='businesstype',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
    ]
