# Generated by Django 5.0.2 on 2026-07-05 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0044_message_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutogrowthKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autogrowth_keywords', to='app_ib.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autogrowth_keywords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='autogrowthkeyword',
            constraint=models.UniqueConstraint(fields=('user', 'term'), name='uniq_autogrowth_user_term'),
        ),
    ]
