# Generated by Django 5.0.2 on 2025-11-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0044_businesscategory_imageurl_businesssegment_imageurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscategory',
            old_name='imageUrl',
            new_name='imageRTUrl',
        ),
        migrations.RenameField(
            model_name='businesssegment',
            old_name='imageUrl',
            new_name='imageRTUrl',
        ),
        migrations.RenameField(
            model_name='businesstype',
            old_name='imageUrl',
            new_name='imageRTUrl',
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='imageSQUrl',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
        migrations.AddField(
            model_name='businesssegment',
            name='imageSQUrl',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
        migrations.AddField(
            model_name='businesstype',
            name='imageSQUrl',
            field=models.CharField(blank=True, max_length=2250, null=True),
        ),
    ]
