# Generated by Django 5.0.2 on 2026-07-05 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0045_autogrowthkeyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('pricingMode', models.CharField(default='custom', max_length=20)),
                ('validUntil', models.DateField(blank=True, null=True)),
                ('fromBlock', models.JSONField(default=dict)),
                ('toBlock', models.JSONField(default=dict)),
                ('lineItems', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gstPercent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gstAmount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grandTotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('terms', models.TextField(blank=True, default='')),
                ('noteToBuyer', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('sentAt', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app_ib.business')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app_ib.leadquery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
