# Generated by Django 5.0.2 on 2025-11-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0045_rename_imageurl_businesscategory_imagerturl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='brandName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
