# Generated by Django 5.0.2 on 2025-11-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0046_business_brandname'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssegment',
            name='businessCategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='business_category_segment', to='app_ib.businesscategory'),
        ),
        migrations.AlterField(
            model_name='business',
            name='businessCategory',
            field=models.ManyToManyField(related_name='business_category', to='app_ib.businesscategory'),
        ),
        migrations.AlterField(
            model_name='business',
            name='businessSegment',
            field=models.ManyToManyField(related_name='business_segment', to='app_ib.businesssegment'),
        ),
    ]
