# Generated by Django 5.0.2 on 2026-07-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0046_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='attributeTags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='replyAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='replyText',
            field=models.TextField(blank=True, default=''),
        ),
    ]
