# Generated by Django 5.0.2 on 2025-11-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0047_businesssegment_businesscategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
