# Generated by Django 5.0.2 on 2026-07-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0047_review_attributetags_review_replyat_review_replytext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supportEmail', models.EmailField(default='help@interiorbazzar.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('tollFree', models.CharField(blank=True, default='', max_length=30)),
                ('officeAddress', models.TextField(blank=True, default='')),
                ('hours', models.CharField(blank=True, default='', max_length=160)),
                ('liveChatAvailable', models.BooleanField(default=False)),
                ('agentCount', models.PositiveIntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Config',
                'verbose_name_plural': 'Support Config',
            },
        ),
    ]
