# Generated by Django 5.0.2 on 2026-07-05 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0049_seed_support_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('displayOrder', models.PositiveIntegerField(db_index=True, default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['displayOrder', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HelpTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(default='ti-help', max_length=60)),
                ('iconBg', models.CharField(default='#e1f5ee', max_length=20)),
                ('iconColor', models.CharField(default='#085041', max_length=20)),
                ('articleCount', models.PositiveIntegerField(default=0)),
                ('displayOrder', models.PositiveIntegerField(db_index=True, default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['displayOrder', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HelpTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('gradient', models.CharField(blank=True, default='', max_length=200)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('views', models.CharField(blank=True, default='', max_length=20)),
                ('videoUrl', models.TextField(blank=True, default='')),
                ('displayOrder', models.PositiveIntegerField(db_index=True, default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['displayOrder', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('lastReplyAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
