# Generated by Django 5.0.2 on 2026-07-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0051_seed_help_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('initials', models.CharField(blank=True, default='', max_length=6)),
                ('gradient', models.CharField(blank=True, default='', max_length=200)),
                ('photoUrl', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('isPlaceholder', models.BooleanField(default=False)),
                ('displayOrder', models.PositiveIntegerField(db_index=True, default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['displayOrder', 'id'],
            },
        ),
    ]
