# Generated by Django 5.0.2 on 2026-07-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0053_seed_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='badgeIcon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='compareRows',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
