# Generated by Django 5.0.2 on 2026-07-07 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0055_seed_v3_plan_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='transectiondata',
            name='refundAmount',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transectiondata',
            name='refundReason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transectiondata',
            name='refundStatus',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transectiondata',
            name='refundedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transectiondata',
            name='refundedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_actioned', to=settings.AUTH_USER_MODEL),
        ),
    ]
