# Generated by Django 5.0.2 on 2026-07-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0056_transectiondata_refundamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='replies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
