# Generated by Django 5.0.2 on 2026-07-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0057_supportticket_replies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='banners',
            name='bannerUrl',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='banners',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
