# Generated by Django 5.0.2 on 2026-07-08 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0059_backfill_subscription_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='transectiondata',
            name='paymentMethod',
            field=models.CharField(default='gateway', max_length=20),
        ),
        migrations.AddField(
            model_name='transectiondata',
            name='verifiedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transectiondata',
            name='verifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
