# Generated by Django 5.0.2 on 2026-07-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0060_transectiondata_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='tier',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1),
        ),
    ]
