# Generated by Django 5.0.2 on 2026-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0061_leadquery_score_leadquery_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssegment',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
