# Generated by Django 5.0.2 on 2026-07-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0063_blog_seo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transectiondata',
            name='proofUrl',
            field=models.TextField(blank=True, default=''),
        ),
    ]
