# Generated by Django 5.0.2 on 2026-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0064_transectiondata_proofurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
