# Generated by Django 5.0.2 on 2026-07-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0065_subscription_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectplan',
            name='durationMonths',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationplan',
            name='durationMonths',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='durationMonths',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopplan',
            name='durationMonths',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlanBillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durationMonths', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('oldPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('badgeLabel', models.CharField(blank=True, default='', max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingCycles', to='app_ib.subscription')),
            ],
            options={
                'ordering': ['durationMonths'],
                'unique_together': {('plan', 'durationMonths')},
            },
        ),
    ]
