# Generated by Django 5.0.2 on 2026-07-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0067_billing_cycles_from_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='timeline',
            field=models.CharField(blank=True, choices=[('30d', 'Within 30 days'), ('90d', '30–90 days'), ('90plus', '90+ days'), ('browsing', 'Just browsing')], default='', max_length=10),
        ),
    ]
