# Generated by Django 5.0.2 on 2026-07-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0070_alter_adpage_table_alter_architect_table_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name='architect',
            name='businesses',
        ),
        migrations.RemoveField(
            model_name='architect',
            name='expertiseTags',
        ),
        migrations.RemoveField(
            model_name='architect',
            name='user',
        ),
        migrations.RemoveField(
            model_name='award',
            name='architect',
        ),
            ],
        ),
    ]
