# Generated by Django 5.0.2 on 2026-07-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0072_alter_automationplan_architect_and_more'),
    ]

    # State-only: the billing models were physically relocated to interior_billing
    # (TASK 14). Tables keep their app_ib_* names and are untouched — the DB already
    # has them. So this only removes the models from app_ib's migration STATE; no DDL.
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.RemoveField(
            model_name='automationplan',
            name='architect',
        ),
        migrations.RemoveField(
            model_name='automationplan',
            name='business',
        ),
        migrations.RemoveField(
            model_name='automationplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='automationplan',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='automationplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='planbillingcycle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='planbillingcycle',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='planquery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shopplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='shopplan',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shopplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transectiondata',
            name='refundedBy',
        ),
        migrations.RemoveField(
            model_name='transectiondata',
            name='verifiedBy',
        ),
        migrations.DeleteModel(
            name='ArchitectPlan',
        ),
        migrations.DeleteModel(
            name='AutomationPlan',
        ),
        migrations.DeleteModel(
            name='BusinessPlan',
        ),
        migrations.DeleteModel(
            name='PlanBillingCycle',
        ),
        migrations.DeleteModel(
            name='PlanQuery',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='ShopPlan',
        ),
        migrations.DeleteModel(
            name='TransectionData',
        ),
        ], database_operations=[]),
    ]
