# Generated by Django 5.0.2 on 2026-07-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0073_remove_automationplan_architect_and_more'),
    ]

    operations = [
        # State-only: leads/CRM models moved to interior_leads (TASK 15). Tables stay.
        migrations.SeparateDatabaseAndState(database_operations=[], state_operations=[
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='FunnelForm',
        ),
        migrations.RemoveField(
            model_name='leadquery',
            name='business',
        ),
        migrations.RemoveField(
            model_name='leadquery',
            name='catalouge',
        ),
        migrations.RemoveField(
            model_name='leadquery',
            name='product',
        ),
        migrations.RemoveField(
            model_name='leadquery',
            name='service',
        ),
        migrations.RemoveField(
            model_name='leadquery',
            name='user',
        ),
        ]),
    ]
