# Generated by Django 5.0.2 on 2026-07-09 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0074_delete_contact_remove_feedback_user_and_more'),
        ('interior_leads', '0001_initial'),
    ]

    operations = [
        # State-only: leads/CRM models moved to interior_leads (TASK 15). Tables stay;
        # conversation.lead now points at the same table under its new app label.
        migrations.SeparateDatabaseAndState(database_operations=[], state_operations=[
        migrations.AlterField(
            model_name='conversation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='interior_leads.leadquery'),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Quate',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='business',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='LeadQuery',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        ]),
    ]
