# Generated by Django 5.0.2 on 2026-07-09 19:05
# Hand-edited (TASK 16): Banners/Constants are dead tables -> REAL DeleteModel
# (drop the tables). The CMS/content models moved to interior_cms -> state-only
# (tables stay; only the app_ib model registration is removed).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0075_alter_conversation_lead_remove_quotation_lead_and_more'),
    ]

    operations = [
        # --- Dead tables: real drop (nothing read them; admin House Banners uses
        # interior_advertisement.HomeHeroBanner, not app_ib.Banners). ---
        migrations.DeleteModel(
            name='Banners',
        ),
        migrations.DeleteModel(
            name='Constants',
        ),
        # --- CMS/content models moved to interior_cms (state-only): the app_ib_*
        # tables are untouched; interior_cms/0001 re-registers them against the
        # same tables. FK removals precede the model deletes so StockMedia's FKs
        # to Page/Section drop from state before those models leave. ---
        migrations.SeparateDatabaseAndState(database_operations=[], state_operations=[
            migrations.RemoveField(
                model_name='blog',
                name='user',
            ),
            migrations.RemoveField(
                model_name='newslettersubscriber',
                name='user',
            ),
            migrations.RemoveField(
                model_name='stockmedia',
                name='page',
            ),
            migrations.RemoveField(
                model_name='stockmedia',
                name='section',
            ),
            migrations.DeleteModel(
                name='OfferHeading',
            ),
            migrations.DeleteModel(
                name='OfferText',
            ),
            migrations.DeleteModel(
                name='OurClients',
            ),
            migrations.DeleteModel(
                name='Pages',
            ),
            migrations.DeleteModel(
                name='QNA',
            ),
            migrations.DeleteModel(
                name='ReelSection',
            ),
            migrations.DeleteModel(
                name='TeamMember',
            ),
            migrations.DeleteModel(
                name='Blog',
            ),
            migrations.DeleteModel(
                name='NewsletterSubscriber',
            ),
            migrations.DeleteModel(
                name='Page',
            ),
            migrations.DeleteModel(
                name='Section',
            ),
            migrations.DeleteModel(
                name='StockMedia',
            ),
        ]),
    ]
