# Generated by Django 5.0.2 on 2026-07-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0076_delete_banners_remove_blog_user_delete_constants_and_more'),
    ]

    # State-only: Notification physically moved to interior_notification with the
    # same pinned db_table (app_ib_notification). No DDL — the table stays put.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Notification',
                ),
            ],
            database_operations=[],
        ),
    ]
