# Generated by Django 5.0.2 on 2026-07-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0077_delete_notification'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.RemoveField(
            model_name='business',
            name='businessBadge',
        ),
        migrations.RemoveField(
            model_name='business',
            name='businessCategory',
        ),
        migrations.RemoveField(
            model_name='business',
            name='businessSegment',
        ),
        migrations.RemoveField(
            model_name='business',
            name='businessType',
        ),
        migrations.RemoveField(
            model_name='business',
            name='expertiseTags',
        ),
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businesssocialmedia',
            name='business',
        ),
            ],
            database_operations=[],
        ),
    ]
