# Generated by Django 5.0.2 on 2026-07-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0078_remove_business_businessbadge_and_more'),
        ('interior_advertisement', '0010_alter_adasset_category_alter_adasset_subcategory_and_more'),
        ('interior_billing', '0002_alter_automationplan_business_and_more'),
        ('interior_business', '0001_initial'),
        ('interior_engine', '0003_alter_architect_businesses_and_more'),
        ('interior_leads', '0002_alter_leadquery_business_alter_quotation_business'),
        ('interior_products', '0015_alter_catelogue_business_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.AlterField(
            model_name='conversation',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='interior_business.business'),
        ),
        migrations.RemoveField(
            model_name='dayschedule',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businesssegment',
            name='businessCategory',
        ),
        migrations.RemoveField(
            model_name='businesssegment',
            name='businessType',
        ),
        migrations.RemoveField(
            model_name='businesssocialmedia',
            name='socialMedia',
        ),
        migrations.RemoveField(
            model_name='location',
            name='locationCountry',
        ),
        migrations.RemoveField(
            model_name='location',
            name='locationState',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.DeleteModel(
            name='BusinessBadge',
        ),
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='DaySchedule',
        ),
        migrations.DeleteModel(
            name='BusinessCategory',
        ),
        migrations.DeleteModel(
            name='BusinessSegment',
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
        migrations.DeleteModel(
            name='BusinessSocialMedia',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
            ],
            database_operations=[],
        ),
    ]
