# Generated by Django 5.0.2 on 2026-07-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0079_alter_conversation_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformad',
            name='page',
        ),
        migrations.DeleteModel(
            name='AdPage',
        ),
        migrations.DeleteModel(
            name='PlatformAd',
        ),
    ]
