# Generated by Django 5.2.10 on 2026-07-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0080_remove_platformad_page_delete_adpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundRobinCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('count', models.BigIntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Round Robin Counter',
                'verbose_name_plural': 'Round Robin Counters',
            },
        ),
    ]
