# Generated by Django 5.0.2 on 2026-07-09 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ib', '0074_delete_contact_remove_feedback_user_and_more'),
        ('interior_products', '0014_alter_product_tags_alter_service_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # State-only: the tables (app_ib_*) already exist — this move keeps them
        # in place and only re-registers the models under interior_leads (TASK 15).
        migrations.SeparateDatabaseAndState(database_operations=[], state_operations=[
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('name', models.CharField(blank=True, max_length=800, null=True)),
                ('phone', models.CharField(blank=True, max_length=800, null=True)),
                ('mail', models.CharField(blank=True, max_length=800, null=True)),
                ('company', models.CharField(blank=True, max_length=800, null=True)),
                ('recognisation', models.CharField(blank=True, max_length=800, null=True)),
                ('detail', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact/attachment')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_contact',
            },
        ),
        migrations.CreateModel(
            name='FunnelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('companyName', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('planType', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('plan', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('intrest', models.TextField(blank=True, default='', null=True)),
                ('need', models.TextField(blank=True, default='', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='New', max_length=255, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_funnelform',
            },
        ),
        migrations.CreateModel(
            name='Quate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadType', models.CharField(default='', max_length=500)),
                ('businessType', models.CharField(default='', max_length=500)),
                ('budget', models.CharField(default='', max_length=500)),
                ('name', models.CharField(default='', max_length=500)),
                ('phoneNumber', models.CharField(default='', max_length=500)),
                ('query', models.TextField(default='')),
                ('email', models.CharField(default='', max_length=500)),
                ('noOfEmp', models.CharField(default='', max_length=500)),
                ('companyName', models.CharField(default='', max_length=500)),
                ('note', models.CharField(default='', max_length=500)),
                ('stage', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leads for company',
                'verbose_name_plural': 'Platform Own Leads',
                'db_table': 'app_ib_quate',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=500)),
                ('feedback', models.TextField()),
                ('status', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_feedback',
            },
        ),
        migrations.CreateModel(
            name='LeadQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('interested', models.TextField(blank=True, default='', null=True)),
                ('query', models.TextField(blank=True, default='', null=True)),
                ('city', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('status', models.TextField(blank=True, default='', null=True)),
                ('leadStatus', models.TextField(blank=True, default='', null=True)),
                ('stage', models.TextField(blank=True, default='', null=True)),
                ('tag', models.TextField(blank=True, default='', null=True)),
                ('priority', models.TextField(blank=True, default='', null=True)),
                ('remark', models.TextField(blank=True, default='', null=True)),
                ('logs', models.JSONField(blank=True, default=list, null=True)),
                ('clientLogs', models.JSONField(blank=True, default=list, help_text="{'by':'client/business','message':'Text message','date':'date in dmy format(02-12-2026)'}", null=True)),
                ('respondedAt', models.DateTimeField(blank=True, null=True)),
                ('sourceChannel', models.CharField(blank=True, default='', max_length=200)),
                ('originType', models.CharField(blank=True, default='', max_length=50)),
                ('originId', models.IntegerField(blank=True, null=True)),
                ('formType', models.CharField(blank=True, default='', max_length=50)),
                ('messageCount', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(blank=True, db_index=True, default='', max_length=1)),
                ('score', models.PositiveIntegerField(default=0)),
                ('timeline', models.CharField(blank=True, choices=[('30d', 'Within 30 days'), ('90d', '30–90 days'), ('90plus', '90+ days'), ('browsing', 'Just browsing')], default='', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_lead_query', to='app_ib.business')),
                ('catalouge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalouge_lead_query', to='interior_products.catelogue')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lead_query', to='interior_products.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_lead_query', to='interior_products.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_lead_query', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_leadquery',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('pricingMode', models.CharField(default='custom', max_length=20)),
                ('validUntil', models.DateField(blank=True, null=True)),
                ('fromBlock', models.JSONField(default=dict)),
                ('toBlock', models.JSONField(default=dict)),
                ('lineItems', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gstPercent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gstAmount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grandTotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('terms', models.TextField(blank=True, default='')),
                ('noteToBuyer', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('sentAt', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app_ib.business')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='interior_leads.leadquery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_quotation',
                'ordering': ['-createdAt'],
            },
        ),
        ]),
    ]
