# Generated by Django 5.0.2 on 2026-07-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_leads', '0002_alter_leadquery_business_alter_quotation_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='dealValueEst',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
