# Generated by Django 5.0.2 on 2026-07-20 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_leads', '0003_leadquery_dealvalueest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Private remark text.')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='interior_leads.leadquery')),
            ],
            options={
                'db_table': 'app_ib_lead_note',
                'ordering': ['-createdAt'],
            },
        ),
    ]
