# Generated by Django 5.0.2 on 2026-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_full_access',
            field=models.BooleanField(default=False),
        ),
    ]
