# Generated by Django 5.0.2 on 2026-07-09 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ib', '0073_remove_automationplan_architect_and_more'),
        ('interior_engine', '0002_relabel_contenttypes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # State-only: these billing models were physically relocated FROM app_ib (TASK 14).
    # Their app_ib_* tables already exist in the DB (created by app_ib's earlier
    # migrations), so we only register the models in interior_billing's migration STATE
    # here — database_operations is empty, no CREATE TABLE runs.
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=800, null=True)),
                ('entityType', models.CharField(blank=True, default='business', max_length=50, null=True)),
                ('planFamily', models.CharField(blank=True, default='business', max_length=50, null=True)),
                ('grantsEntityTypes', models.JSONField(blank=True, default=list, null=True)),
                ('tier', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(blank=True, max_length=800, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=800, null=True)),
                ('services', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=800, null=True)),
                ('tag', models.CharField(blank=True, max_length=800, null=True)),
                ('amount', models.CharField(blank=True, max_length=800, null=True)),
                ('leadcount', models.IntegerField(blank=True, default=0, null=True)),
                ('discountPercentage', models.CharField(blank=True, max_length=800, null=True)),
                ('discountAmount', models.CharField(blank=True, max_length=800, null=True)),
                ('payableAmount', models.CharField(blank=True, max_length=800, null=True)),
                ('availableDuration', models.JSONField(blank=True, default=list, help_text="List of objects with duration and price. Example: [{'duration': 3, 'price': 100}, {'duration': 6, 'price': 180}]", null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('badgeIcon', models.CharField(blank=True, max_length=100, null=True)),
                ('compareRows', models.JSONField(blank=True, default=dict)),
                ('fallbackImageUrl', models.URLField(blank=True, max_length=2250, null=True)),
                ('videoUrl', models.URLField(blank=True, max_length=2250, null=True)),
                ('planPdfUrl', models.URLField(blank=True, max_length=2250, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_subscription',
            },
        ),
        migrations.CreateModel(
            name='PlanQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default='', max_length=500)),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=500)),
                ('country', models.CharField(default='', max_length=500)),
                ('address', models.TextField(default='')),
                ('transactionId', models.CharField(default='', max_length=500)),
                ('stage', models.CharField(default='', max_length=500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lead_query/attachment')),
                ('attachmentUrl', models.URLField(blank=True, default='', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_planquery',
            },
        ),
        migrations.CreateModel(
            name='ShopPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(blank=True, default='')),
                ('amount', models.CharField(default='', max_length=500)),
                ('durationMonths', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('isActive', models.BooleanField(default=False)),
                ('transactionId', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('planSummary', models.TextField(blank=True, default='')),
                ('lastActivate', models.DateTimeField(auto_now_add=True)),
                ('expireDate', models.DateTimeField(blank=True, null=True)),
                ('buyIntent', models.CharField(blank=True, default='website', max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_plan', to='interior_engine.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_plans', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior_billing.subscription')),
            ],
            options={
                'db_table': 'app_ib_shopplan',
            },
        ),
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField()),
                ('amount', models.CharField(default='', max_length=500)),
                ('durationMonths', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('isActive', models.BooleanField(default=False)),
                ('transactionId', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('planSummary', models.TextField()),
                ('lastActivate', models.DateTimeField(auto_now_add=True)),
                ('expireDate', models.DateTimeField(blank=True, null=True)),
                ('buyIntent', models.CharField(blank=True, default='website', max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_plan', to='app_ib.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_plans', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior_billing.subscription')),
            ],
            options={
                'db_table': 'app_ib_businessplan',
            },
        ),
        migrations.CreateModel(
            name='AutomationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(blank=True, default='')),
                ('amount', models.CharField(default='', max_length=500)),
                ('durationMonths', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('isActive', models.BooleanField(default=False)),
                ('transactionId', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('planSummary', models.TextField(blank=True, default='')),
                ('lastActivate', models.DateTimeField(auto_now_add=True)),
                ('expireDate', models.DateTimeField(blank=True, null=True)),
                ('buyIntent', models.CharField(blank=True, default='website', max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_plan', to='interior_engine.architect')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_plan', to='app_ib.business')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_plan', to='interior_engine.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_plans', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior_billing.subscription')),
            ],
            options={
                'db_table': 'app_ib_automationplan',
            },
        ),
        migrations.CreateModel(
            name='ArchitectPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(blank=True, default='')),
                ('amount', models.CharField(default='', max_length=500)),
                ('durationMonths', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('isActive', models.BooleanField(default=False)),
                ('transactionId', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('planSummary', models.TextField(blank=True, default='')),
                ('lastActivate', models.DateTimeField(auto_now_add=True)),
                ('expireDate', models.DateTimeField(blank=True, null=True)),
                ('buyIntent', models.CharField(blank=True, default='website', max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='architect_plan', to='interior_engine.architect')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='architect_plans', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior_billing.subscription')),
            ],
            options={
                'db_table': 'app_ib_architectplan',
            },
        ),
        migrations.CreateModel(
            name='TransectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(default='', max_length=500)),
                ('transactionId', models.CharField(default='', max_length=500)),
                ('amount', models.CharField(default='', max_length=500)),
                ('paymentFor', models.CharField(default='', max_length=500)),
                ('createdAt', models.DateTimeField()),
                ('expiryAt', models.DateTimeField()),
                ('orderStatus', models.CharField(default='', max_length=500)),
                ('paymentSessionId', models.CharField(default='', max_length=1000)),
                ('planFamily', models.CharField(blank=True, default='', max_length=50)),
                ('refundStatus', models.CharField(blank=True, default='', max_length=50)),
                ('refundAmount', models.CharField(blank=True, default='', max_length=500)),
                ('refundReason', models.TextField(blank=True, default='')),
                ('refundedAt', models.DateTimeField(blank=True, null=True)),
                ('paymentMethod', models.CharField(default='gateway', max_length=20)),
                ('proofUrl', models.TextField(blank=True, default='')),
                ('verifiedAt', models.DateTimeField(blank=True, null=True)),
                ('refundedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_actioned', to=settings.AUTH_USER_MODEL)),
                ('verifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_transectiondata',
            },
        ),
        migrations.CreateModel(
            name='PlanBillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durationMonths', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('oldPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('badgeLabel', models.CharField(blank=True, default='', max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingCycles', to='interior_billing.subscription')),
            ],
            options={
                'db_table': 'app_ib_planbillingcycle',
                'ordering': ['durationMonths'],
                'unique_together': {('plan', 'durationMonths')},
            },
        ),
        ], database_operations=[]),
    ]
