# Generated by Django 5.0.2 on 2026-07-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_billing', '0001_initial'),
        ('interior_business', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.AlterField(
            model_name='automationplan',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_plan', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='businessplan',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_plan', to='interior_business.business'),
        ),
            ],
            database_operations=[],
        ),
    ]
