# Generated by Django 5.0.2 on 2026-07-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_billing', '0002_alter_automationplan_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50, unique=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_planpagesection',
                'ordering': ['family'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='cardContent',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
