# Generated by Django 5.0.2 on 2025-11-18 08:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdApprovalMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdAssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('placementId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('dailyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aspectRatio', models.CharField(choices=[('16:9', '16:9'), ('4:3', '4:3'), ('1:1', '1:1')], default='1:1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('days', models.IntegerField()),
                ('priceTotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adCampaigns', to='app_ib.business')),
                ('approvalMode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_advertisement.adapprovalmode')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adCampaigns', to='interior_advertisement.adplacement')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_advertisement.adstatus')),
            ],
        ),
        migrations.CreateModel(
            name='AdAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3Key', models.TextField()),
                ('meta', models.JSONField(default=dict)),
                ('assetType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_advertisement.adassettype')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='interior_advertisement.adcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentProvider', models.TextField()),
                ('transactionId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True)),
                ('paymentReference', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='interior_advertisement.adcampaign')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_advertisement.adpaymentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='AdPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('ageBetween', models.CharField(blank=True, max_length=50, null=True)),
                ('personaType', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='interior_advertisement.adcampaign')),
                ('categories', models.ManyToManyField(blank=True, to='app_ib.businesscategory')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_ib.businesssegment')),
            ],
        ),
        migrations.CreateModel(
            name='AdStatAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('formSubmissions', models.IntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='interior_advertisement.adcampaign')),
            ],
            options={
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AdStatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userSessionId', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='interior_advertisement.adcampaign')),
                ('eventType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interior_advertisement.adeventtype')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'eventType'], name='interior_ad_campaig_073e40_idx')],
            },
        ),
    ]
