# Generated by Django 5.0.2 on 2026-01-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0011_businesscategory_shortvalue_and_more'),
        ('interior_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adasset',
            name='category',
            field=models.ManyToManyField(to='app_ib.businesscategory'),
        ),
        migrations.AddField(
            model_name='adasset',
            name='subCategory',
            field=models.ManyToManyField(to='app_ib.businesssegment'),
        ),
    ]
