# Generated by Django 5.0.2 on 2025-11-04 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpayment',
            name='transactionId',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True),
        ),
    ]
