# Generated by Django 5.0.2 on 2026-01-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_advertisement', '0002_adasset_category_adasset_subcategory'),
        ('interior_products', '0004_productcategory_shortvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adasset',
            name='productCategory',
            field=models.ManyToManyField(to='interior_products.productcategory'),
        ),
        migrations.AddField(
            model_name='adasset',
            name='productSubCategory',
            field=models.ManyToManyField(to='interior_products.productsubcategory'),
        ),
    ]
