# Generated by Django 5.0.2 on 2026-06-11 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0023_adpage_conversation_firstresponseseconds_platformad'),
        ('interior_advertisement', '0003_adasset_productcategory_adasset_productsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('backgroundGradient', models.CharField(blank=True, default='', max_length=255)),
                ('backgroundImageUrl', models.TextField(blank=True, default='')),
                ('displayOrder', models.PositiveIntegerField(db_index=True, default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('startsAt', models.DateTimeField(blank=True, null=True)),
                ('endsAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('businesses', models.ManyToManyField(blank=True, related_name='heroBanners', to='app_ib.business')),
            ],
            options={
                'verbose_name': 'Home Hero Banner',
                'verbose_name_plural': 'Home Hero Banners',
                'ordering': ['displayOrder', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BannerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='interior_advertisement.homeherobanner')),
            ],
            options={
                'verbose_name': 'Banner Metric',
                'verbose_name_plural': 'Banner Metrics',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BannerButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('link', models.TextField(blank=True, default='')),
                ('isPrimary', models.BooleanField(default=False)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='interior_advertisement.homeherobanner')),
            ],
            options={
                'verbose_name': 'Banner Button',
                'verbose_name_plural': 'Banner Buttons',
                'ordering': ['-isPrimary', 'id'],
            },
        ),
    ]
