# Generated by Django 5.0.2 on 2026-07-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_advertisement', '0006_seed_home_hero_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='rejectReason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
