# Generated by Django 5.0.2 on 2026-07-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_advertisement', '0007_adcampaign_rejectreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeherobanner',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('buyers', 'Signed-in buyers'), ('sellers', 'Business owners')], db_index=True, default='all', max_length=10),
        ),
    ]
