# Generated by Django 5.0.2 on 2026-07-08 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0059_backfill_subscription_isactive'),
        ('interior_advertisement', '0008_homeherobanner_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='page',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adCampaigns', to='app_ib.business'),
        ),
    ]
