# Generated by Django 5.0.2 on 2026-07-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_advertisement', '0009_adcampaign_page_alter_adcampaign_advertiser'),
        ('interior_business', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.AlterField(
            model_name='adasset',
            name='category',
            field=models.ManyToManyField(to='interior_business.businesscategory'),
        ),
        migrations.AlterField(
            model_name='adasset',
            name='subCategory',
            field=models.ManyToManyField(to='interior_business.businesssegment'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adCampaigns', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='adpersona',
            name='categories',
            field=models.ManyToManyField(blank=True, to='interior_business.businesscategory'),
        ),
        migrations.AlterField(
            model_name='adpersona',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interior_business.businesssegment'),
        ),
        migrations.AlterField(
            model_name='homeherobanner',
            name='businesses',
            field=models.ManyToManyField(blank=True, related_name='heroBanners', to='interior_business.business'),
        ),
            ],
            database_operations=[],
        ),
    ]
