# Generated by Django 5.0.2 on 2026-07-09 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ib', '0071_remove_architect_businesses_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('interior_products', '0013_product_careinstructions_product_installationsteps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listKey', models.CharField(db_index=True, max_length=100)),
                ('snapshotDate', models.DateField()),
                ('payload', models.JSONField(default=dict)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_dailysnapshot',
            },
        ),
        migrations.CreateModel(
            name='Differentiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('iconBg', models.CharField(blank=True, default='', max_length=40)),
                ('iconColor', models.CharField(blank=True, default='', max_length=40)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('eliminates', models.JSONField(blank=True, default=list)),
                ('index', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_differentiator',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EditorsPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('eyebrow', models.CharField(default='', max_length=255)),
                ('headline', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
                ('trendTags', models.JSONField(blank=True, default=list)),
                ('imageUrl', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='template', max_length=20)),
                ('isPublished', models.BooleanField(default=True)),
                ('isAiEdited', models.BooleanField(default=False)),
                ('snapshotDate', models.DateField()),
            ],
            options={
                'db_table': 'app_ib_editorspick',
            },
        ),
        migrations.CreateModel(
            name='EngagementActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('actorName', models.CharField(blank=True, default='', max_length=255)),
                ('verb', models.CharField(max_length=20)),
                ('entityType', models.CharField(blank=True, default='', max_length=20)),
                ('entityName', models.CharField(blank=True, default='', max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('isRead', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'app_ib_engagementactivity',
            },
        ),
        migrations.CreateModel(
            name='FallbackVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoUrl', models.TextField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_ib_fallbackvideo',
            },
        ),
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField(blank=True, null=True)),
                ('eventType', models.CharField(max_length=20)),
                ('template', models.CharField(max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('isSynthetic', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'app_ib_feedevent',
            },
        ),
        migrations.CreateModel(
            name='JoinUsCta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='', max_length=200)),
                ('titleLead', models.CharField(blank=True, default='', max_length=200)),
                ('titleAccent', models.CharField(blank=True, default='', max_length=200)),
                ('sub', models.TextField(blank=True, default='')),
                ('primaryLabel', models.CharField(blank=True, default='', max_length=100)),
                ('primaryAction', models.JSONField(blank=True, default=dict)),
                ('secondaryLabel', models.CharField(blank=True, default='', max_length=100)),
                ('secondaryAction', models.JSONField(blank=True, default=dict)),
                ('trustBadges', models.JSONField(blank=True, default=list)),
                ('cardHead', models.CharField(blank=True, default='', max_length=200)),
                ('responseNote', models.CharField(blank=True, default='', max_length=300)),
                ('isActive', models.BooleanField(default=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_joinuscta',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JoinUsStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=40)),
                ('value', models.TextField(blank=True, default='')),
                ('index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'app_ib_joinusstep',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('boardType', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('scope', models.CharField(default='global', max_length=20)),
                ('entityType', models.CharField(max_length=20)),
                ('displayName', models.CharField(default='', max_length=255)),
                ('imageUrl', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('genuineViews', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('computedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_leaderboardentry',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'app_ib_platform',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepNumber', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('index', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_ib_processstep',
                'ordering': ['index', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('coverImage', models.TextField(blank=True, default='')),
                ('images', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('style', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('viewCount', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_project',
                'ordering': ['index', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('viewedAt', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'app_ib_recentlyviewed',
            },
        ),
        migrations.CreateModel(
            name='RelatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceObjectId', models.PositiveIntegerField(db_index=True)),
                ('targetObjectId', models.PositiveIntegerField()),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('reason', models.CharField(default='co_view', max_length=20)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_relateditem',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('isVerifiedPurchase', models.BooleanField(default=False)),
                ('helpfulCount', models.PositiveIntegerField(default=0)),
                ('isApproved', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('replyText', models.TextField(blank=True, default='')),
                ('replyAt', models.DateTimeField(blank=True, null=True)),
                ('attributeTags', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_review',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.TextField()),
                ('index', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'app_ib_reviewimage',
            },
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_ib_saveditem',
            },
        ),
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(blank=True, default='', max_length=64)),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('normalizedQuery', models.CharField(db_index=True, max_length=500)),
                ('resultCount', models.PositiveIntegerField(default=0)),
                ('clickedResultType', models.CharField(blank=True, default='', max_length=20)),
                ('clickedResultId', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'app_ib_searchevent',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('shopType', models.CharField(default='offline', max_length=20)),
                ('bio', models.TextField(blank=True, default='')),
                ('coverImage', models.TextField(blank=True, default='')),
                ('bannerImage', models.TextField(blank=True, default='')),
                ('bannerLink', models.TextField(blank=True, default='')),
                ('isActive', models.BooleanField(default=True)),
                ('isPrimary', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('viewCount', models.PositiveIntegerField(default=0)),
                ('leadCount', models.PositiveIntegerField(default=0)),
                ('trendingScore', models.FloatField(db_index=True, default=0.0)),
                ('hotScore', models.FloatField(db_index=True, default=0.0)),
                ('rating', models.FloatField(default=0.0)),
                ('totalReviews', models.PositiveIntegerField(default=0)),
                ('ratingBreakdown', models.JSONField(blank=True, default=dict)),
                ('completionPercent', models.PositiveIntegerField(default=0)),
                ('canGoLive', models.BooleanField(default=False)),
                ('avgResponseSeconds', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.TextField()),
                ('index', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_ib_shopimage',
                'ordering': ['index', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShopQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(blank=True, default='')),
                ('askedBy', models.CharField(blank=True, default='', max_length=120)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_ib_shopquestion',
                'ordering': ['displayOrder', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShopUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('badge', models.CharField(blank=True, default='', max_length=60)),
                ('color', models.CharField(blank=True, default='', max_length=40)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_ib_shopupdate',
                'ordering': ['displayOrder', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShortVideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('videoUrl', models.TextField()),
                ('isPrimary', models.BooleanField(default=False)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_ib_shortvideolink',
            },
        ),
        migrations.CreateModel(
            name='SpecializationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityType', models.CharField(default='business', max_length=20)),
                ('scheduledAt', models.DateTimeField(db_index=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=50)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lastError', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_specializationjob',
            },
        ),
        migrations.CreateModel(
            name='SyntheticEventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
                ('weight', models.PositiveIntegerField(default=1)),
                ('eventType', models.CharField(default='synthetic', max_length=20)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_ib_syntheticeventtemplate',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('usageCount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'app_ib_tag',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoUrl', models.TextField()),
                ('thumbnailUrl', models.TextField(blank=True, default='')),
                ('authorName', models.CharField(max_length=150)),
                ('authorRole', models.CharField(blank=True, default='', max_length=150)),
                ('businessName', models.CharField(blank=True, default='', max_length=200)),
                ('quote', models.TextField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('isActive', models.BooleanField(default=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_ib_testimonial',
                'ordering': ['index', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrendingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('period', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_ib_trendingscore',
            },
        ),
        migrations.CreateModel(
            name='ViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('sessionId', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('dwellSeconds', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'app_ib_viewevent',
            },
        ),
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('coverImage', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('totalReviews', models.PositiveIntegerField(default=0)),
                ('ratingBreakdown', models.JSONField(blank=True, default=dict)),
                ('trendingScore', models.FloatField(db_index=True, default=0.0)),
                ('hotScore', models.FloatField(db_index=True, default=0.0)),
                ('viewCount', models.PositiveIntegerField(default=0)),
                ('leadCount', models.PositiveIntegerField(default=0)),
                ('completionPercent', models.PositiveIntegerField(default=0)),
                ('canGoLive', models.BooleanField(default=False)),
                ('avgResponseSeconds', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('businesses', models.ManyToManyField(blank=True, related_name='linked_architects', to='app_ib.business')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_architect', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_architect',
            },
        ),
        migrations.CreateModel(
            name='AutogrowthKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autogrowth_keywords', to='app_ib.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autogrowth_keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_autogrowthkeyword',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('imageUrl', models.TextField(blank=True, default='')),
                ('kind', models.CharField(default='award', max_length=20)),
                ('index', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='interior_engine.architect')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='app_ib.business')),
            ],
            options={
                'db_table': 'app_ib_award',
                'ordering': ['index', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BehindTheTrendStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('rankFrom', models.PositiveIntegerField(blank=True, null=True)),
                ('rankTo', models.PositiveIntegerField(blank=True, null=True)),
                ('windowLabel', models.CharField(default='', max_length=100)),
                ('planAtCompute', models.CharField(default='', max_length=50)),
                ('imageUrl', models.TextField(blank=True, default='')),
                ('enquiryGrowthPct', models.FloatField(blank=True, null=True)),
                ('headline', models.CharField(default='', max_length=255)),
                ('eyebrow', models.CharField(default='', max_length=255)),
                ('storyTitle', models.CharField(default='', max_length=255)),
                ('storyBody', models.TextField(default='')),
                ('trendTags', models.JSONField(blank=True, default=list)),
                ('isPublished', models.BooleanField(default=True)),
                ('isAiEdited', models.BooleanField(default=False)),
                ('snapshotDate', models.DateField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_stories', to='app_ib.business')),
            ],
            options={
                'db_table': 'app_ib_behindthetrendstory',
            },
        ),
        migrations.CreateModel(
            name='BusinessAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('date', models.DateField(db_index=True)),
                ('viewCount', models.PositiveIntegerField(default=0)),
                ('uniqueVisitorCount', models.PositiveIntegerField(default=0)),
                ('leadCount', models.PositiveIntegerField(default=0)),
                ('quoteCount', models.PositiveIntegerField(default=0)),
                ('whatsappTapCount', models.PositiveIntegerField(default=0)),
                ('callTapCount', models.PositiveIntegerField(default=0)),
                ('saveCount', models.PositiveIntegerField(default=0)),
                ('enquiryGrowthPct', models.FloatField(blank=True, null=True)),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'app_ib_businessanalytics',
            },
        ),
        migrations.CreateModel(
            name='BusinessSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.JSONField(blank=True, default=list)),
                ('profileSnapshot', models.TextField(blank=True, default='')),
                ('snapshotHash', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(default='template', max_length=20)),
                ('generatedAt', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='app_ib.business')),
            ],
            options={
                'db_table': 'app_ib_businessspecialization',
            },
        ),
        migrations.CreateModel(
            name='BusinessTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='staff', max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='app_ib.business')),
                ('invitedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_businessteammember',
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('sessionId', models.CharField(blank=True, default='', max_length=64)),
                ('clickType', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ib_clickevent',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('isPrimary', models.BooleanField(default=False)),
                ('countryCode', models.CharField(default='+91', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('website', models.URLField(blank=True, default='')),
                ('gmb', models.URLField(blank=True, default='')),
                ('workingPlaceLink', models.URLField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='interior_engine.architect')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='app_ib.business')),
            ],
            options={
                'db_table': 'app_ib_contactinfo',
            },
        ),
        migrations.AddConstraint(
            model_name='dailysnapshot',
            constraint=models.UniqueConstraint(fields=('listKey', 'snapshotDate'), name='uniq_daily_snapshot'),
        ),
        migrations.AddField(
            model_name='editorspick',
            name='architect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors_picks', to='interior_engine.architect'),
        ),
        migrations.AddField(
            model_name='engagementactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementactivity',
            name='contentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='engagementactivity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedevent',
            name='contentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='joinusstep',
            name='joinUs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='interior_engine.joinuscta'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='contentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='fallbackvideo',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior_engine.platform'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_steps', to='interior_engine.architect'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_steps', to='app_ib.business'),
        ),
        migrations.AddField(
            model_name='project',
            name='architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='interior_engine.architect'),
        ),
        migrations.AddField(
            model_name='project',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app_ib.business'),
        ),
        migrations.AddField(
            model_name='recentlyviewed',
            name='contentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='recentlyviewed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recently_viewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relateditem',
            name='sourceContentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_source', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='relateditem',
            name='targetContentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_target', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='review',
            name='architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='interior_engine.architect'),
        ),
        migrations.AddField(
            model_name='review',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='app_ib.business'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='interior_products.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='interior_products.service'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='interior_engine.review'),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='contentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_shops', to='app_ib.business'),
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='interior_engine.shop'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_steps', to='interior_engine.shop'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='interior_engine.shop'),
        ),
        migrations.AddField(
            model_name='award',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='interior_engine.shop'),
        ),
        migrations.AddField(
            model_name='shopimage',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='interior_engine.shop'),
        ),
        migrations.AddField(
            model_name='shopquestion',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interior_engine.shop'),
        ),
        migrations.AddField(
            model_name='shopupdate',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='interior_engine.shop'),
        ),
        migrations.AddField(
            model_name='shortvideolink',
            name='contentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='shortvideolink',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior_engine.platform'),
        ),
        migrations.AddField(
            model_name='specializationjob',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_jobs', to='app_ib.business'),
        ),
        migrations.AddField(
            model_name='shop',
            name='expertiseTags',
            field=models.ManyToManyField(blank=True, related_name='expert_shops', to='interior_engine.tag'),
        ),
        migrations.AddField(
            model_name='architect',
            name='expertiseTags',
            field=models.ManyToManyField(blank=True, related_name='expert_architects', to='interior_engine.tag'),
        ),
        migrations.AddField(
            model_name='trendingscore',
            name='contentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='viewevent',
            name='contentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='viewevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='autogrowthkeyword',
            constraint=models.UniqueConstraint(fields=('user', 'term'), name='uniq_autogrowth_user_term'),
        ),
        migrations.AddConstraint(
            model_name='businessanalytics',
            constraint=models.UniqueConstraint(fields=('contentType', 'objectId', 'date'), name='uniq_business_analytics_day'),
        ),
        migrations.AddConstraint(
            model_name='businessteammember',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='uniq_team_member'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['contentType', 'objectId', 'timestamp'], name='app_ib_clic_content_5f9140_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorspick',
            constraint=models.UniqueConstraint(fields=('architect', 'snapshotDate'), name='uniq_editors_pick_day'),
        ),
        migrations.AddIndex(
            model_name='engagementactivity',
            index=models.Index(fields=['owner', 'timestamp'], name='app_ib_enga_owner_i_a55b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementactivity',
            index=models.Index(fields=['owner', 'isRead'], name='app_ib_enga_owner_i_4b6715_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(fields=('boardType', 'period', 'scope', 'contentType', 'objectId'), name='uniq_leaderboard_entry'),
        ),
        migrations.AddConstraint(
            model_name='recentlyviewed',
            constraint=models.UniqueConstraint(fields=('user', 'contentType', 'objectId'), name='uniq_recently_viewed'),
        ),
        migrations.AddIndex(
            model_name='relateditem',
            index=models.Index(fields=['sourceContentType', 'sourceObjectId', 'score'], name='app_ib_rela_sourceC_22ab5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='relateditem',
            constraint=models.UniqueConstraint(fields=('sourceContentType', 'sourceObjectId', 'targetContentType', 'targetObjectId'), name='uniq_related_pair'),
        ),
        migrations.AddConstraint(
            model_name='saveditem',
            constraint=models.UniqueConstraint(fields=('user', 'contentType', 'objectId'), name='uniq_saved_item'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['business'], name='app_ib_revi_busines_24cf70_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['shop'], name='app_ib_revi_shop_id_d9c07b_idx'),
        ),
        migrations.AddIndex(
            model_name='specializationjob',
            index=models.Index(fields=['status', 'scheduledAt'], name='app_ib_spec_status_8627f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='trendingscore',
            constraint=models.UniqueConstraint(fields=('contentType', 'objectId', 'period', 'city'), name='uniq_trendingscore_entity_period_city'),
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['contentType', 'objectId', 'timestamp'], name='app_ib_view_content_df4614_idx'),
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['city', 'timestamp'], name='app_ib_view_city_61ac42_idx'),
        ),
            ],
        ),
    ]
