# Generated by Django 5.0.2 on 2026-07-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_business', '0001_initial'),
        ('interior_engine', '0002_relabel_contenttypes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.AlterField(
            model_name='architect',
            name='businesses',
            field=models.ManyToManyField(blank=True, related_name='linked_architects', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='autogrowthkeyword',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autogrowth_keywords', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='award',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='behindthetrendstory',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_stories', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='businessspecialization',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='businessteammember',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_steps', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='project',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='review',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_shops', to='interior_business.business'),
        ),
        migrations.AlterField(
            model_name='specializationjob',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_jobs', to='interior_business.business'),
        ),
            ],
            database_operations=[],
        ),
    ]
