# Generated by Django 5.0.2 on 2026-07-15 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_engine', '0003_alter_architect_businesses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text="Package name, e.g. 'Full home design'. Blank for a single default package.", max_length=120)),
                ('fromValue', models.PositiveIntegerField(blank=True, help_text="Starting project value in rupees → 'New projects from ₹X'.", null=True)),
                ('typicalTimeline', models.CharField(blank=True, default='', help_text="Typical timeline for this package, e.g. '2–3 weeks'.", max_length=80)),
                ('freeConsultation', models.BooleanField(default=False, help_text='This package includes a free initial consultation.')),
                ('description', models.TextField(blank=True, default='')),
                ('index', models.PositiveIntegerField(default=0, help_text='Display order; lowest = primary.')),
                ('isActive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='interior_engine.architect')),
            ],
            options={
                'db_table': 'app_ib_architect_package',
                'ordering': ['index', 'id'],
            },
        ),
    ]
