# Generated by Django 5.0.2 on 2026-07-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_engine', '0004_architectpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='1=Monday..7=Sunday')),
                ('openTime', models.TimeField(blank=True, help_text='null = closed this day', null=True)),
                ('closeTime', models.TimeField(blank=True, null=True)),
                ('isClosed', models.BooleanField(default=False, help_text='Explicit closed toggle')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='interior_engine.shop')),
            ],
            options={
                'db_table': 'app_ib_shop_day_schedule',
                'ordering': ['day'],
                'unique_together': {('shop', 'day')},
            },
        ),
    ]
