# Generated by Django 5.0.2 on 2026-07-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_engine', '0005_shop_day_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text="List of amenity ids, e.g. ['parking', 'wifi']."),
        ),
        migrations.AddField(
            model_name='shop',
            name='appointmentRequired',
            field=models.BooleanField(default=False, help_text='Appointment preferred for walk-ins.'),
        ),
        migrations.AddField(
            model_name='shop',
            name='holidayMode',
            field=models.BooleanField(default=False, help_text='Pauses new enquiries without resetting hours.'),
        ),
        migrations.AddField(
            model_name='shop',
            name='walkInBooking',
            field=models.BooleanField(default=False, help_text='Allow walk-in visitors during open hours.'),
        ),
        migrations.AddField(
            model_name='shop',
            name='walkInLeadTime',
            field=models.CharField(blank=True, default='', help_text="Lead time for walk-ins, e.g. '15min'.", max_length=50),
        ),
    ]
