# Generated by Django 5.0.2 on 2026-07-09 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Delete-then-create: app_ib drops Notification from its state first, then
        # this migration adds it to interior_notification's state (same table).
        ('app_ib', '0077_delete_notification'),
    ]

    # State-only: the app_ib_notification table already exists (created by
    # app_ib migration 0019). This move only re-labels the model's app in Django's
    # state — database_operations=[] so no CREATE TABLE runs.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('type', models.CharField(max_length=20)),
                        ('title', models.CharField(max_length=255)),
                        ('body', models.TextField(blank=True, default='')),
                        ('actionUrl', models.CharField(blank=True, default='', max_length=500)),
                        ('dedupeKey', models.CharField(blank=True, default='', max_length=255)),
                        ('groupCount', models.PositiveIntegerField(default=1)),
                        ('metadata', models.JSONField(blank=True, default=dict)),
                        ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'app_ib_notification',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
