# Generated by Django 5.0.2 on 2026-04-17 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GMBBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=255)),
                ('rating', models.CharField(help_text='Store in format 4.8(32)', max_length=50)),
                ('ratingValue', models.FloatField(default=0.0)),
                ('reviewCount', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('mapLink', models.URLField(blank=True, null=True)),
                ('socialLinks', models.JSONField(blank=True, default=list)),
                ('waMessage', models.URLField(blank=True, null=True)),
                ('rankingRate', models.FloatField(default=0.0)),
                ('tier', models.CharField(blank=True, max_length=1, null=True)),
                ('platform', models.CharField(default='GMB', max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('logs', models.JSONField(blank=True, default=list, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('assignedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gmb_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GMB Business',
                'verbose_name_plural': 'GMB Businesses',
            },
        ),
        migrations.CreateModel(
            name='GMBActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='System', max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='interior_admin.gmbbusiness')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
