# Generated by Django 5.0.2 on 2026-04-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmbbusiness',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gmbbusiness',
            name='platform',
            field=models.CharField(db_index=True, default='GMB', max_length=100),
        ),
        migrations.AlterField(
            model_name='gmbbusiness',
            name='rankingRate',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='gmbbusiness',
            name='tier',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
    ]
