# Generated by Django 5.0.2 on 2026-04-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmbbusiness',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
