# Generated by Django 5.0.2 on 2026-04-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0002_gmbbusiness_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmbbusiness',
            name='socialLinks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
