# Generated by Django 5.0.2 on 2026-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0003_alter_gmbbusiness_sociallinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmbbusiness',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
