# Generated by Django 5.0.2 on 2026-04-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0004_gmbbusiness_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmbbusiness',
            name='businessName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gmbbusiness',
            name='mapLink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gmbbusiness',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gmbbusiness',
            name='waMessage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gmbbusiness',
            name='web',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
