# Generated by Django 5.0.2 on 2026-07-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0006_adminauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, unique=True)),
                ('channel', models.CharField(default='email', max_length=50)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('variables', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
