# Generated by Django 5.0.2 on 2026-07-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0007_notificationtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoUrl', models.URLField(blank=True, default='', max_length=1000)),
                ('faviconUrl', models.URLField(blank=True, default='', max_length=1000)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
