# Generated by Django 5.0.2 on 2026-07-07 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0008_brandasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=150)),
                ('region', models.CharField(db_index=True, max_length=150)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'region'],
                'unique_together': {('category', 'region')},
            },
        ),
    ]
