# Generated by Django 5.0.2 on 2026-07-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0009_slotinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
