# Generated by Django 5.0.2 on 2026-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0011_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('quote', models.TextField()),
                ('type', models.CharField(default='text', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('avatarUrl', models.URLField(blank=True, default='', max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-createdAt'],
            },
        ),
    ]
