# Generated by Django 5.0.2 on 2026-07-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0013_listingreport'),
        ('rbac_module', '0002_role_is_full_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleKey', models.CharField(db_index=True, max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='rbac_module.role')),
            ],
            options={
                'unique_together': {('role', 'moduleKey')},
            },
        ),
    ]
