# Generated by Django 5.0.2 on 2026-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0014_adminmoduleaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='dltId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
