# Generated by Django 5.0.2 on 2026-07-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0015_notificationtemplate_dltid_notificationtemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgLifetimeMonths', models.PositiveIntegerField(default=18)),
                ('grossMargin', models.DecimalField(decimal_places=2, default=0.7, max_digits=4)),
                ('revenueTarget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('newCustomersThisMonth', models.PositiveIntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='kind',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('reinvestment', 'Reinvestment')], default='fixed', max_length=20),
        ),
    ]
