# Generated by Django 5.0.2 on 2026-07-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0016_revenueassumption_expense_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='businessName',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='index',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='videoUrl',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
