# Generated by Django 5.0.2 on 2026-07-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_admin', '0017_alter_testimonial_options_testimonial_businessname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('imageUrl', models.URLField(max_length=1000)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('activeFrom', models.DateField(blank=True, null=True)),
                ('activeTo', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-activeFrom', '-createdAt'],
            },
        ),
        migrations.AddField(
            model_name='brandasset',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
